#! /usr/bin/env python3

from options.separator import get_separator
from scripts.pane import Pane, Panes
from scripts.theme import get_background, get_background_inactive, get_color
from scripts.tmux import set_global, set_window_global
from scripts.utils import make_style

def pane_status(col1, col2, bold=False):
    sections = []
    if not separator.is_set():
        sections.append(make_style(" ", bg=background, bold=bool(bold)))
    else:
        sections.append(make_style(left, bg=col1, fg=background, bold=bool(bold)))
    sections.append(make_style(" #I | ", bg=col1, fg=col2, bold=bool(bold)))
    sections.append(make_style("#W ", fg=col2, bold=bool(bold)))
    sections.append(make_style(left, bg=background, fg=col1, bold=bool(bold)))

    return "".join(sections)

separator = get_separator()
left = separator.left()
right = separator.right()

primary = get_color()
background = get_background()
background2 = get_background_inactive()

panes_left = Panes(foreground=primary, background=background)
panes_left.add(Pane("path", "#{b:pane_current_path}", background=primary, foreground=background))

panes_right = Panes(foreground=primary, background=background)
panes_right.add(Pane("path", "#S", background=primary, foreground=background))
panes_right.add(Pane("path", "#H", background=primary, foreground=background))

# Set the background and foreground colors of the statusline
set_global("status-style", f"bg={background},fg={primary}")
set_global("window-status-separator", "")

# Set the left side of the statusline
set_global("status-left", panes_left.print("left", separator))
set_global("status-left-length", "60")

# Set the right side of the statusline
set_global("status-right", panes_right.print("right", separator))


set_global("pane-border-style", f"fg={background}")
set_global("pane-active-border-style", f"fg={primary}")

set_global("message-command-style", f"fg={primary} bg={background}")
set_global("message-style", f"fg={primary} bg={background}")
set_global("mode-style", f"fg={primary} bg={background}")


# Set the window list colors and style
set_window_global("window-status-style", f"bg={background},fg={primary}")
set_window_global("window-status-format", pane_status(background2, primary, True))

set_window_global("window-status-current-style", f"bg={primary},fg={primary}")
set_window_global("window-status-current-format", pane_status(primary, background, True))
